### ISSUE TITLE
AppConfigProcessor to expose LastConfigVersion as part of the GetDataAsync

### ISSUE THREAD

**Issue by alexpap** [aws/aws-dotnet-extensions-configuration#105]
## Describe the Feature
Would be nice if the _AppConfigProcessor_ as part of the _GetDataAsync_   
to append/update the latest config version retrieved

### Is your Feature Request related to a problem?
Currently there is no way to know   
what was the latest aws app config version retrieved/reloaded for the specified  
<application, environment, profile, client>

## Proposed Solution
AppConfigProcessor could have a reserved configuration key  
(e.g. ApplicationId_EnvironmentId_ProfileId_ClientId) to add as part of the returned LastConfig

* [x] :wave: I may be able to implement this feature request

**Comment by ashishdhingra** [comment]
@alexpap Could you please review [comment](https://github.com/aws/aws-dotnet-extensions-configuration/pull/106#issuecomment-1097450984) in PR https://github.com/aws/aws-dotnet-extensions-configuration/pull/106 by @normj. Not sure if this feature request is valid any more.

**Comment by alexpap** [comment]
Hi @ashishdhingra, thanks for checking this feature request.

with the [pull request](https://github.com/aws/aws-dotnet-extensions-configuration/pull/103), the suggested solution is not valid, but the feature request for having the latest version retrieved its quite useful for audit purposes.

Maybe a similar patch to [this](https://github.com/aws/aws-dotnet-extensions-configuration/pull/106/files) can be applied to expose the latest version retrieved or at least we can have the latest version retrieved as log info.

what do you think ?

**Comment by mgorski-mg** [comment]
@alexpap the problem is that it's not available in AppConfig API in the current implementation of getting configuration as @normj wrote in PR #106.
The current implementation uses only tokens so you don't need to send the version all the time, but you are also not getting version information in the response.

You can check the response of GetLatestConfiguration [here](https://docs.aws.amazon.com/appconfig/2019-10-09/APIReference/API_appconfigdata_GetLatestConfiguration.html#API_appconfigdata_GetLatestConfiguration_ResponseElements).

The response has only
- ContentType
- NextPollConfigurationToken
- NextPollIntervalInSeconds
- Configuration

**Comment by ashishdhingra** [comment]
@mgorski-mg Thanks for your inputs above.
@alexpap Please review inputs in https://github.com/aws/aws-dotnet-extensions-configuration/issues/105#issuecomment-1325683312 and confirm if it's good to close this issue.
