### ISSUE TITLE
ssm:GetParametersByPath permission is required

### ISSUE THREAD

**Issue by ajstokar** [aws/aws-dotnet-extensions-configuration#108]
## Description

Without adding - ssm:GetParametersByPath to my role within cloudformation template, I get the following error message

`Amazon.SimpleSystemsManagement.AmazonSimpleSystemsManagementException: User: arn:aws:sts::010375052143:assumed-role/api-dev-taskrole/b3d2288234f84e6890309f446b99639f is not authorized to perform: ssm:GetParametersByPath on resource: arn:aws:ssm:us-east-1:010375052143:parameter/ommyx/dev because no identity-based policy allows the ssm:GetParametersByPath action`

## Reproduction Steps

Deploy with SAM

### Environment

* Build Version: 3.0.0
* OS Info:OSX
* Build Environment: AWS SAM
* Targeted .NET Platform:  

## Resolution
- [ ] :wave: I can/would-like-to implement a fix for this problem myself

Add -ssm:GetParametersByPath to the role definition.  

Please update the docs with this info, I wasted a full day debugging.

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Hi @ajstokar,

Good morning.

Could you please share the reproduction steps along with sample code that uses [Amazon.Extensions.Configuration.SystemsManager](https://www.nuget.org/packages/Amazon.Extensions.Configuration.SystemsManager/) package, in the below format?



## Expected Behavior



## Current Behavior






## Possible Solution



## Steps to Reproduce (for bugs)





## Context



## Your Environment

* AWSSDK.Core version used: 
* Service assembly and version used: 
* Operating System and version: 
* Visual Studio version: 
* Targeted .NET platform: 

## .NET Core Info

* .NET Core version used for development: 
* .NET Core version installed in the environment where application runs: 
* Output of `dotnet --info`: 
* Contents of project.json/project.csproj: 

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

You also specified deployment with SAM and need to update role definition to add `-ssm:GetParametersByPath`. Could you please elaborate with an example deployment configuration along with steps? Kindly review if this issued needs to be transferred or reopened in https://github.com/aws/aws-sam-cli repository since this repository is for [Amazon.Extensions.Configuration.SystemsManager](https://www.nuget.org/packages/Amazon.Extensions.Configuration.SystemsManager/) package.

Thanks,
Ashish
