### ISSUE TITLE
ReloadAfter doesn't work in Lambda

### ISSUE THREAD

**Issue by MonneOnrust** [aws/aws-dotnet-extensions-configuration#17]
The ReloadAfter functionality in SystemsManagerConfigurationProvider doesn't work if the code runs in AWS Lambda. Parameter values remain the same during the lifetime of the Lambda instance. It works fine if I run the code locally on my development machine. 

We would very much like this to work, since you can't force a Lambda-function to restart and load the new configuration values.

**Comment by MonneOnrust** [comment]
Hi Ken, 
As part of an ASP.NET Core application hosted on Lambda. In Visual Studio, I do Add new project, then AWS Lambda->AWS Serverless Application and then ASP.NET Core Web API.

**Comment by KenHundley** [comment]
Ok, I'll try to take a quick look tonight. 

It should work without issue, however, because of the way lambda freezes code execution between calls it would cause a delay on the reload until the code is executed again. Future executions "should" allow everything to catch up at that later time. However, because of the delay, the first call back to the app could use the old data since the reload would have just started and likely wouldn't have finished yet. I'll verify this is the case and there isn't some other issue happening. 

Assuming this is causing what you are seeing then there is Good news and Bad news:
1) Bad news: I don't think there is anything that can be done since it's a behaviour of Lambda
2) Good news: The more active the app is the more it's kept alive, and the sooner it'll reload.

I'll try to get this verified

**Comment by MonneOnrust** [comment]
Hi Ken,

Did you have the chance to take a look at this already?

Outlook voor Android<https://aka.ms/ghei36> downloaden

________________________________

**Comment by KenHundley** [comment]
Unfortunately I’ve been tied up with work and worked late the last couple nights.

**Comment by KenHundley** [comment]
ok, I reproduced what you saw and that it matches what I described. I was also able to confirm that keeping traffic flowing to the app kept it awake and allowed the refresh to happen as expected.

So basically the issue is that since the refresh happens in the background it's "trying" to do it, but depending on how fast your request finishes it can't finish the refresh. Then when you make a later request it tries again, but if it can't finish it'll get delayed again. However, if the app keeps a steady flow of traffic then it gets the time it needs to succeed and the values will be updated as expected.

I'll need the AWS team's input on what they want to do for this situation. They are all busy with re:Invent, so it could be a bit before they respond.

**Comment by KenHundley** [comment]
Actually I have a suggestion if you want to see it function.

Add this Middleware near the start of your request pipeline
```csharp
app.Use(async (context, next) =>
{
    await Task.Delay(1000);
    await next.Invoke();
});
```
That will induce a small lag at the start of the request, which should give the refresh time to finish. I know this is hacky and not a permemant solution, but you should be able to verify that it did run.

**Comment by normj** [comment]
I'm thinking in the `Amazon.Lambda.AspNetCoreServer` bridge library we could check to see if one of the configuration providers was this provider. Then we need a mechanism on this provider to see if a reload is pending and if so wait for the reload to occur before processing the request. Another trick will be is `Amazon.Lambda.AspNetCoreServer` can't take a dependency on this provider so we might have to do this using reflection.

**Comment by jiabiao** [comment]
We use Task.Yield() to hanlder similar situation：
```csharp
    public class Function
    {
        List<DateTime> History { get; set; } = new List<DateTime>();

        public Function()
        {
            ChangeToken.OnChange(() =>
            {
                var cancellationTokenSource = new CancellationTokenSource(TimeSpan.FromSeconds(20));
                var cancellationChangeToken = new CancellationChangeToken(cancellationTokenSource.Token);
                return cancellationChangeToken;
            }, () =>
            {
                History.Add(DateTime.Now);                
            });
        }

        public async Task<List<DateTime>> FunctionHandler(string input, ILambdaContext context)
        {
            await Task.Yield();
            return History;
        }
    }
```

**Comment by KenHundley** [comment]
I have a different approach that could possibly work and wouldn't require changes to `Amazon.Lambda.AspNetCoreServer`. I believe we could add a middleware class that would allow them to add it anywhere in the request pipeline in the startup class. That only that that middleware will do is look for a refresh and wait for the signal before calling next().  

This way there are no additional dependancies in other packages, the middleware can be in the same package and the provider, and people can choose whether or not they want to add it to the request pipeline or not.

The only danger I see is that if a refresh started and 50 requests come in all those request would be blocked from completing until the refresh finished.

Thoughts?

**Comment by normj** [comment]
Correct if I'm wrong but if you add the handler to this package then it has to take a dependency in ASP.NET Core packages which I would not want to avoid. Also I think we only want this behavior in Lambda which has this special case of the compute environment freezing. We need to make sure we don't confuse anybody running their application in something besides Lambda to not use this handler.

What I was playing around with today is updating the refresh code to use a `ManualResetEvent` object around the refresh code.

```csharp
if (source.ReloadAfter != null)
{
    ChangeToken.OnChange(() =>
    {
        var cancellationTokenSource = new CancellationTokenSource(source.ReloadAfter.Value);
        var cancellationChangeToken = new CancellationChangeToken(cancellationTokenSource.Token);
        return cancellationChangeToken;
    }, async () =>
    {
        ReloadTaskEvent.Reset();
        try
        {
            await LoadAsync(true).ConfigureAwait(false);
        }
        finally
        {
            ReloadTaskEvent.Set();
        }
    });
}
```

And then have a new public method to wait on
```
public void WaitForReloadToComplete(TimeSpan timeout)
{
    ReloadTaskEvent.WaitOne(timeout);
}
```

The `Amazon.Lambda.AspNetCoreServer` can look for that public method and call it at the end of every request which would be a noop except for when a reload is performed.

**Comment by KenHundley** [comment]
Yep, you're correct. I thought there was a middleware structure that only needed an anonymous delegate, but they all either require a `HttpContext`, `RequestDelegate`, or both. So that would require a reference to `Microsoft.AspNetCore.Http.Abstractions`

One thing to keep in mind with your solution is multiple registrations and making sure they don't block each other.

**Comment by normj** [comment]
Unless you can think of an objection why don't I make the change to have the `WaitForReloadToComplete` and then separately we can update `Amazon.Lambda.AspNetCoreServer`. We are trying to get this out soon and I don't want to block the release on this but I would like to have at least this hook before we release.  Does that work for @KenHundley and @MonneOnrust?

**Comment by normj** [comment]
I checked in this change to expose the `WaitForReloadToComplete` method.

**Comment by normj** [comment]
I also added a [PR](https://github.com/aws/aws-dotnet-extensions-configuration/pull/22) that would expose a utility method that would be easy to call from simple Lambda functions to ensure the reload happens.

**Comment by KenHundley** [comment]
Hey @MonneOnrust,
Are you using `IOptionsSnapshot` or `IOptionsMonitor`? `IOptions` does not allow for reloading data. `IOptions` are static once they are created.

[.Net Configuration Documentation](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-2.2)

Also, there is a [sample project](https://github.com/aws/aws-dotnet-extensions-configuration/tree/master/samples) in this repo you can look at, but it's using IOptions since it wasn't built with reload in mind. Just replace `IOptions` with `IOptionsSnapshot` or `IOptionsMonitor` and it should work with reload.

**Comment by MonneOnrust** [comment]
Hi @KenHundley 
I'm just doing configuration["settingkey"], where configuration is the IConfiguration object I have built. So the most basic call.

**Comment by MonneOnrust** [comment]
Hi @KenHundley 
Do you agree that the scenario with the IConfiguration object should just work and can you please try to reproduce my findings?

**Comment by KenHundley** [comment]
Hey @MonneOnrust, 

Sry I've been swamped at work and just had a chance to test this today. I was able to confirm that it worked for me, however, I did not test it directly in Lambda since it takes more time to set up. I'll try to do a Lambda test by Wednesday.

Maybe someone from the AWS side can help confirm this as well.

**Comment by KenHundley** [comment]
Actually, I was able to test this out tonight. The reload worked fine for me and I was able to see the changes reflected in the responses.

It did take 2 queries to see it, however. The first one allowed the update to occur but used the original values since the reload was "underway", and the following request reflected that change

**Comment by KenHundley** [comment]
How are you calling `Configuration.WaitForSystemsManagerReloadToComplete`?

You will need to make sure it's executed with each call to the function before it returns. If this is in an ASP.Net app you'll need to incorporate it into the request pipeline. 

I did this with a call like 
```
app.Use(async (context, next) =>
{
    await Task.Run(() => Configuration.WaitForSystemsManagerReloadToComplete(TimeSpan.FromSeconds(5)));
    await next.Invoke();
    await Task.Run(() => Configuration.WaitForSystemsManagerReloadToComplete(TimeSpan.FromSeconds(5)));
});
```
This will cause it to wait for the reload before or after the request if a reload is pending. 

You don't need both calls, but if no reload is pending then it'll return instantly. The important thing is to pause the request flow until the reload is complete

**Comment by KenHundley** [comment]
Also, if this doesn't help solve the problem I would suggest reopening the ticket so others see there is still a discussion ongoing.

**Comment by MonneOnrust** [comment]
Okay, I got it to work now. I must have tested it with the wrong configuration or something like that. I'm sorry for the inconvenience and extra effort.

**Comment by monnecc** [comment]
Been testing with this again and it still doesn't work. I've downloaded the code from the SDK and put tracing in, but in Lambda you just can't say reload after 60 seconds implementing it with a cancellationtoken. After 60 seconds, the cancellationtoken does nothing if your lambda executions are short.

**Comment by klaytaybai** [comment]
> Been testing with this again and it still doesn't work. I've downloaded the code from the SDK and put tracing in, but in Lambda you just can't say reload after 60 seconds implementing it with a cancellationtoken. After 60 seconds, the cancellationtoken does nothing if your lambda executions are short.

@monnecc, have you followed all the guidance above?

**Comment by monnecc** [comment]
Yes, I have. I was the original reporter, so I was in the loop all the time.

**Comment by monnecc** [comment]
By the way, this isn't a feature request, it's a bug. It doesn't work as the documentation states.

**Comment by monnecc** [comment]
@normj maybe you can help, since @klaytaybai doesn't provide support anymore.

**Comment by savanvadalia** [comment]
@NGL321, any updates on this issue?

As per @KenHundley guidance I can confirm that even after adding below  I wasn't able to refresh the value in lambda environment.

```
app.Use(async (context, next) =>
{
    await Task.Run(() => Configuration.WaitForSystemsManagerReloadToComplete(TimeSpan.FromSeconds(5)));
    await next.Invoke();
    await Task.Run(() => Configuration.WaitForSystemsManagerReloadToComplete(TimeSpan.FromSeconds(5)));
});

```
I am also using `IOptionsSnapshot` as advised.

So to test this I set my reload Interval to every 3 minutes, and I send request to Asp.Net Core lambda intentionally when it is outside the 3 minute hit mark reload interval. I capture and log the Current DateTime just before calling SDK extension method `builder.AddSystemsManager()` in the Api Startup.cs just before calling so I know that which time interval I don't trigger the request to fail the reload. e.g. if my App booted at 6:03:23 pm then I would keep sending request at on 6:04:24, 6:07:24, 6:10:24  likewise.  

I couldn't get the value refreshed for at least 10 subsequent requests and when it did reload it didn't even reload at the 3 minutes interval frequency, it was some time outside the 3 minute interval so I am not sure how the reload is handled under the hood.

From my tests I can say that`WaitForSystemsManagerReloadToComplete` extension method doesn't fix the issue.

Can someone please help with this or propose possible workaround?

**Comment by ashishdhingra** [comment]
Another similar issue reported https://github.com/aws/aws-dotnet-extensions-configuration/issues/79
