### ISSUE TITLE
OnChange is called when no changes occurred

### ISSUE THREAD

**Issue by timje** [aws/aws-dotnet-extensions-configuration#29]
If using "ReloadAfter" the OnChange is called even when nothing has changed. Ideally should only call OnChange token when the underlying value actually changed.

**Comment by KenHundley** [comment]
The executing code has no way to know beforehand if the values have changed in the Parameter Store, so it must query them to get their current state even if nothing has changed. This OnChange event is that trigger.

**Comment by timje** [comment]
https://github.com/aws/aws-dotnet-extensions-configuration/blob/4e190598663201fbc8e56cc600af0fb706fff953/src/Amazon.Extensions.Configuration.SystemsManager/SystemsManagerConfigurationProvider.cs#L112

Could you compare before/after and see if "Data" changed? Then only call OnReload if it changed?

**Comment by KenHundley** [comment]
ok, got it. So the issue you are having is because the OnReload method is getting called. I can look at adding a before and after comparison here and only execute the OnReload if the Dictionaries are different. 

Can I ask what issue you are getting from the current code? I'd like to understand exactly what's happening currently so that I can ensure the issue is resolved after a code change.

**Comment by timje** [comment]
Great thanks! I'm subscribing to IOptionsMonitor.OnChange and clearing some cached data when this occurs (because the cached data was populated based on the parameters). But this doesn't work as expected, since the OnChange is fired every "reloadAfter" seconds.
