### ISSUE TITLE
Does this library support pulling in AWS region from the default profile?

### ISSUE THREAD

**Issue by mitchogaard** [aws/aws-dotnet-extensions-configuration#49]
Just as the title asks, does this library support pulling in AWS region from the default profile?

I have the default AWS profile set up on my machine for my user (via .aws/config file) and this library did not seem to recognize that my region was configured there. I ended up having to add configuration for it in my appsettings.json file--which isn't ideal.

Thanks in advance.

**Comment by KenHundley** [comment]
There is an open issue about this on the AWS .Net SDK project: https://github.com/aws/aws-sdk-net/issues/1349

**Comment by klaytaybai** [comment]
Hi @mitchogaard, thank you for bringing more attention to this.  I do think it is a bug related to aws/aws-sdk-net#1349, but it looks like the suggestion there to use [profile default] still won't help because there is extra logic to exclude setting the RegionEndpoint if not defined in the AWSOptions.  I'll follow up again with the team to discuss if we can address this without breaking others.

**Comment by whoiskevinrich** [comment]
This is an issue for my group as well.

**Comment by NGL321** [comment]
Hey @mitchogaard / @whoiskevinrich,

We have pushed several updates since last comment. Are you still experiencing this issue with the latest SDK using the default profile?

😸 😷
