### ISSUE TITLE
Use IAM Role credentials instead of profile

### ISSUE THREAD

**Issue by virshu** [aws/aws-dotnet-extensions-configuration#71]
## Describe the Feature
When the application is deployed to the server, it is good security practice to use IAM Role when deployed to EC2 instance, rather than user profile. I assume that this is not possible.

### Is your Feature Request related to a problem?
Keeping Credentials in the profile on the server is bad security approach, and AWS recommends against it. Additionally, the keys need to updated when they are rotated. 

## Proposed Solution
Probably, extend AWSOptions class to specify that the permissions are derived from IAM Role, and not Porfile

### Describe alternatives you've considered
I used AWSSDK.SimpleSystemsManagement package instead; but it didn't work for me. I needed Role credentials to retrieve database credentials from SSM Parameter Store. I was able to accomplish the result in DBContext:OnConfiguring, but I need to do that in the Startup:ConfigureServices while setting up Dependency Injection

## Additional Context
At this time we are going to store DB credentials in appsettings.json, which is not a good security practice.

### Environment
ASP.NET Core application

---

This is a :rocket: Feature Request

**Comment by NGL321** [comment]
Hey @virshu,

Thank you for submitting this request. After brief review, it seems like a reasonable feature to add to the library.

I will pass this along to the development team, but if you would like to see it sooner, and would like to contribute, feel free to make a PR and I will review when I can!


😸 😷

**Comment by ConnorJBishop** [comment]
This is already supported, albeit not in an obvious way.

When you call the `AddSystemsManager` extension method don't specify any AWSOptions. That way when your app runs in production it will automatically obtain credentials from the instance role. 

You can still use profile based credentials for development by adding an AWS section in your **appsettings.development.json** like so:

    "AWS" : {
        "Profile" : "your-dev-profile",
        "Region": "eu-west-2"
    }

This works because this library is referencing the core AWS SDK libraries and using them under the hood. You can read more about how the .NET Core SDK retrieves credentials [here](https://docs.aws.amazon.com/sdk-for-net/latest/developer-guide/net-dg-config-netcore.html). The important bit being:

> Notice that one of the files added to your project is appsettings.Development.json. This corresponds to an EnvironmentName set to Development. During development, you put your configuration in this file, which is only read during local testing. When you deploy an Amazon EC2 instance that has EnvironmentName set to Production, this file is ignored and the AWS SDK for .NET falls back to the IAM credentials and Region that are configured for the Amazon EC2 instance.
