### ISSUE TITLE
Saving configuration, loading on demand

### ISSUE THREAD

**Issue by kkd83** [aws/aws-dotnet-extensions-configuration#81]
Is there a way that configuration can be saved/updated using this library? The Data dictionary is updated but there is no call to update or create the parameter. 

The second one is for lambda loading the entire configuration is quite time consuming when you may not need to load anything for that invocation. Is there a way to do load on demand rather than load all at start-up?

### Expected Behaviour
1. `configuration["myFeature"] = "false";` 
Makes a call to PutParameter and saves the change to Parameter Store

2. `var config = configuration["myFeature"]` 
Gets parameter on demand. Rather than a background task to get the parameters.

### Current Behavior
Change is made locally, and the value stored in the `ConfigurationProvider` data.

### Possible Solution
1. Override `void Set(string key, string value)` in Configuration Provider, check if the key exists, update in parameter store. Keep in mind that all sources are called with Set() so a check must be made to whether we should save it. 
We run an installer to set values rather than using CDK so a switch to create the parameter would be useful. Don't really wish to use a different library to get configuration than to set it. 

2. On TryGet() either populate the Data in one go or preferably just get all parameters with this prefix. Keeping track of what's been downloaded already would be difficult but for lambda the runtime is crucial. 

### Your Environment
AWSSDK.Core version: 3.3.0.0+
Amazon.Extensions.Configuration.SystemsManager: 2.0

### .NET Core Info
SDK 3.1.300

**Comment by ashishdhingra** [comment]
Hi,

I will try to see if I can find anything. In the meanwhile, please share the details in the following format (along with sample code):




## Expected Behavior



## Current Behavior






## Possible Solution



## Steps to Reproduce (for bugs)





## Context



## Your Environment

* AWSSDK.Core version used: 
* Service assembly and version used: 
* Operating System and version: 
* Visual Studio version: 
* Targeted .NET platform: 

## .NET Core Info

* .NET Core version used for development: 
* .NET Core version installed in the environment where application runs: 
* Output of `dotnet --info`: 
* Contents of project.json/project.csproj: 

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html


Thanks,
Ashish

**Comment by kkd83** [comment]
Updated my original comment.

**Comment by ashishdhingra** [comment]
Hi @kkd83,

Looking at the code and available documentation resources, I don't thin using Systems Manager Extensions library to save the parameter values to Parameter Store. One possible reason is that setting up and storing parameters in System Manager is an infrastructure action rather than access action. Hence, storing/updating parameters might be available in CDK, it is not available in other SDKs.

I don't see any option for lazy load. If you want to load the parameters manually, you may refer one of the test code https://github.com/aws/aws-dotnet-extensions-configuration/blob/5e685243ea91613680a04bb227aa9e91c2eb26bf/test/Amazon.Extensions.Configuration.SystemsManager.Integ/ConfigurationBuilderIntegrationTests.cs#L34 to see on how to manually load it. I'm not sure if it works.

Thanks,
Ashish

**Comment by kkd83** [comment]
Hi Ashish, 

Not really sure why getting/setting/updating/deleting(?!) of parameters should be limited to an infrastructure operation - we store system and tenant configuration in the parameter store which can be updated by the tenant or by us including feature flags. This isn't really infrastructure. 

I'm not sure if you are saying that this library does not and will not be extended to support updating of parameters or just that it currently does not support this with no opinion on future plans?

Thanks for replying.

**Comment by ashishdhingra** [comment]
Hi @kkd83,

Thanks for your reply. Except CDK, I do not see any other .NET SDK supporting updating parameters in system manager parameter store. If requested, you may convert this to `feature-request` (remove `guidance` label) and contribute any changes, which can be reviewed by development team. 

Regards,
Ashish

**Comment by kkd83** [comment]
Thanks Ashish, I'll have to use the client to do a direct update and creation, though as someone said its a large dependency. Might submit a change request if that's desired by others to support an update (not create) as its a small change that's supported by the underlying frameworks.

**Comment by ashishdhingra** [comment]
Hi @kkd83,

Please advise if we can close this issue and you will create a new feature request whenever your contributing change is ready, OR, if you would like to convert this issue to feature request.

Thanks,
Ashish
