### ISSUE TITLE
Config path expected: ,  Resource temporarily unavailable while running the app in EKS

### ISSUE THREAD

**Issue by ameer-thasthahir** [aws/aws-dotnet-extensions-configuration#94]
Hi, Facing the same issue while running it in EKS? Any adivce?

_Originally posted by @ameer-thasthahir in https://github.com/aws/aws-dotnet-extensions-configuration/issues/63#issuecomment-865705482_

**Comment by ashishdhingra** [comment]
Hi @ameer-thasthahir,

Good morning.

Could you please share the reproduction steps, including how did you configure the EKS cluster along with all the settings (preferably in the following format), to reproduce the issue?



## Expected Behavior



## Current Behavior






## Possible Solution



## Steps to Reproduce (for bugs)





## Context



## Your Environment

* AWSSDK.Core version used: 
* Service assembly and version used: 
* Operating System and version: 
* Visual Studio version: 
* Targeted .NET platform: 

## .NET Core Info

* .NET Core version used for development: 
* .NET Core version installed in the environment where application runs: 
* Output of `dotnet --info`: 
* Contents of project.json/project.csproj: 

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

Thanks,
Ashish
