### ISSUE TITLE
Is there a dev mode that works with local config?

### ISSUE THREAD

**Issue by AndAShape** [aws/aws-dotnet-extensions-configuration#98]
Is there a way of pulling config from my local machine so that my dev doesn't require a cloud service?

**Comment by ashishdhingra** [comment]
Hi @AndAShape,

Good morning.

Could you please elaborate your question, preferably in the following format?



## Expected Behavior



## Current Behavior






## Possible Solution



## Steps to Reproduce (for bugs)





## Context



## Your Environment

* AWSSDK.Core version used: 
* Service assembly and version used: 
* Operating System and version: 
* Visual Studio version: 
* Targeted .NET platform: 

## .NET Core Info

* .NET Core version used for development: 
* .NET Core version installed in the environment where application runs: 
* Output of `dotnet --info`: 
* Contents of project.json/project.csproj: 

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

Thanks,
Ashish
